[package]
name = "skunkworks_test_runner"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9.4"
definitions = { path = "../definitions" }

[features]
